#/bin/python3
print("            /\ ") 
print("           /  \ ") 
print("          /    \ ") 
print("         /      \ ") 
print("        /        \ ") 
print("       /          \ ") 
print("      /            \ ") 
print("     /              \ ") 
print("    /                \ ") 
print("   /                  \ ") 
print("  /                    \ ") 
print(" /                      \ ") 
print("/________________________\ ") 
print("triangle go brr")
input()
